FROM scratch

ENV CHARTS_SERVICE_PORT 8080
ENV CHARTS_SERVICE_HEALTH_PORT 8082

EXPOSE $CHARTS_SERVICE_PORT
EXPOSE $CHARTS_SERVICE_HEALTH_PORT

COPY charts-server /
ADD packages/ /var/lib/charts/

CMD ["/charts-server"]
